server:
  port: 4003
spring:
  profiles:
    active: study
  application:
    name: user
  config:
    import: optional:configserver:http://config.taskoo.net
  jpa:
    hibernate:
      dll-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel3.cloudtype.app:30867/gym?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 6g2llfz0tu0j

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
eureka:
 instance:
   instance-id: user-microservice-instance
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://eureka.taskoo.net/eureka
