server:
  port: 4003
spring:
  profiles:
    active: study
  application:
    name: user
  config:
    import: optional:configserver:http://config.taskoo.net
  jpa:
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel3.cloudtype.app:30867/gym?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 6g2llfz0tu0j
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
 instance:
   instance-id: user-microservice-instance
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka
     # defaultZone: http://eureka.taskoo.net/eureka


