server:
  port: 0
spring:
  profiles:
    active: study
  application:
    name: user
  config:
    import: optional:configserver:http://config.taskoo.net
  jpa:
    hibernate:
      dll-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel3.cloudtype.app:30867/gym?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 6g2llfz0tu0j
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    #    prefix : classpath:templates/
    #    suffix : .html
    cache: false
#    check-template-location: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # eureka에 등록되는 id 값
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.taskoo.net/eureka # 서비스를 등록할 Eureka 서버 주소를 지정
      # defaultZone: http://localhost:8761/eureka


token:
  expiration_time: 864000000
  secret: user_token

welcome:
  message: Welcome to MSA study User Service.

logging:
  level:
    com.example.user: DEBUG